name: 'sjra62'

config-version: 2
version: '0.1'

profile: 'starrocks_profile'

test-paths: ["tests"]
model-paths: ["models"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  sjra62:

    cqdg:
      materialized: table
      +enabled: false

    1000g:
      materialized: table

    staging:
      materialized: view
