starrocks_profile:
  target: dev
  outputs:
    dev:
      type: starrocks
      host: "{{ env_var('CQDG_STARROCKS_HOST') }}"
      port: 9040
      schema: "{{ env_var('CQDG_STARROCKS_SCHEMA') }}"
      username: "{{ env_var('CQDG_STARROCKS_USER') }}"
      password: "{{ env_var('CQDG_STARROCKS_PASSWORD') }}"
      is_async: true
      async_query_timeout: 3600 # 1 hour