starrocks_profile:
  target: dev
  outputs:
    dev:
      type: starrocks
      host: "{{ env_var('CQDG_STARROCKS_HOST') }}"
      port: "{{ env_var('CQDG_STARROCKS_PORT') }}"
      schema: "{{ env_var('CQDG_STARROCKS_SCHEMA') }}"
      username: "{{ env_var('CQDG_STARROCKS_USER') }}"
      password: "{{ env_var('CQDG_STARROCKS_PASSWORD') }}"