version: 2

models:

  - name: stg_clinvar
    description: ""
    columns:
      - name: chromosome
        description: ""

      - name: start
        description: ""

      - name: reference
        description: ""

      - name: alternate
        description: ""

      - name: interpretations
        description: ""

  - name: stg_variants
    description: ""
    columns:
      - name: chromosome
        description: ""

      - name: start
        description: ""

      - name: reference
        description: ""

      - name: alternate
        description: ""
      - name: variant_class
        description: ""

      - name: hgvsg
        description: ""

      - name: rsnumber
        description: ""

      - name: symbol
        description: ""

      - name: consequences
        description: ""

      - name: mane_select
        description: ""

      - name: canonical
        description: ""

      - name: dna_change
        description: ""

      - name: locus
        description: ""

      - name: hash
        description: ""

  - name: stg_gnomad_genomes_v3
    description: ""
    columns:
      - name: chromosome
        description: ""

      - name: start
        description: ""

      - name: reference
        description: ""

      - name: alternate
        description: ""

      - name: af
        description: ""

  - name: stg_occurences
    description: ""
    columns:

      - name: sample_id
        description: ""

      - name: chromosome
        description: ""

      - name: start
        description: ""


      - name: reference
        description: ""

      - name: alternate
        description: ""

      - name: hgvsg
        description: ""

      - name: variant_class
        description: ""

      - name: name
        description: ""

      - name: calls
        description: ""

      - name: filters
        description: ""

      - name: info_ac
        description: ""

      - name: info_an
        description: ""

      - name: info_af
        description: ""

      - name: has_alt
        description: ""

      - name: locus
        description: ""

      - name: hash
        description: ""

      - name: zygosity
        description: ""

      - name: ad_total
        description: ""

      - name: ad_ratio
        description: ""

      - name: ad_alt
        description: ""

      - name: ad_ref
        description: ""

      - name: info_r2_5p_bias
        description: ""

      - name: info_excess_fs
        description: ""

      - name: info_read_pos_rank_sum
        description: ""

      - name: info_qd
        description: ""

      - name: info_mq
        description: ""

      - name: info_baseq_rank_sum
        description: ""

      - name: info_excess_het
        description: ""

      - name: info_fraction_informative_reads
        description: ""

      - name: info_vqslod
        description: ""

      - name: info_m_qrank_sum
        description: ""

      - name: info_dp
        description: ""

      - name: info_ds
        description: ""

      - name: info_mleaf
        description: ""

      - name: info_mleac
        description: ""

      - name: info_haplotype_score
        description: ""

      - name: info_inbreed_coeff
        description: ""

      - name: info_culprit
        description: ""

      - name: part
        description: ""

      - name: seq_id
        description: ""

  - name: linked_clinvar
    description: ""
    columns:

      - name: locus_id
        description: ""

      - name: interpretations
        description: ""

      - name: locus
        description: ""

      - name: hash
        description: ""

  - name: linked_gnomad_genomes_v3
    description: ""
    columns:

      - name: locus_id
        description: ""

      - name: locus
        description: ""

      - name: hash
        description: ""

      - name: af
        description: ""
