version: 2

models:

  - name: linked_clinvar
    description: ""
    columns:

      - name: locus_id
        description: ""

      - name: interpretations
        description: ""

      - name: locus
        description: ""

      - name: hash
        description: ""

  - name: linked_gnomad_genomes_v3
    description: ""
    columns:

      - name: locus_id
        description: ""

      - name: locus
        description: ""

      - name: hash
        description: ""

      - name: af
        description: ""
